SELECT C.CAR_ID CAR_ID, 
       C.CAR_TYPE CAR_TYPE,
       ROUND(C.DAILY_FEE*30*(100-D.DISCOUNT_RATE)/100) FEE

FROM CAR_RENTAL_COMPANY_CAR C 
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID

WHERE C.CAR_ID NOT IN (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD') 
  AND START_DATE < TO_DATE('2022-11-30', 'YYYY-MM-DD')) AND D.DURATION_TYPE LIKE '30%' 
GROUP BY C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, D.DISCOUNT_RATE 
HAVING C.CAR_TYPE IN ('세단','SUV')
    AND (C.DAILY_FEE*30*(100-D.DISCOUNT_RATE)/100>=500000 AND C.DAILY_FEE*30*(100-D.DISCOUNT_RATE)/100< 2000000)
    
ORDER BY FEE DESC,CAR_TYPE, CAR_TYPE DESC;