-- 코드를 입력하세요
SELECT USER_ID,NICKNAME,
    CITY||' '||STREET_ADDRESS1||' '||STREET_ADDRESS2 AS "전체주소",
    REGEXP_REPLACE(TLNO,'(.{3})(.+)(.{4})', '\1-\2-\3') AS "전화번호"
FROM USED_GOODS_USER U ,(
        SELECT WRITER_ID,COUNT(BOARD_ID) 
        FROM USED_GOODS_BOARD
        GROUP BY WRITER_ID
        HAVING COUNT(BOARD_ID) >=3
    ) W
WHERE W.WRITER_ID = U.USER_ID 
ORDER BY USER_ID DESC