WITH USER_2021 AS(
    SELECT USER_ID
    FROM USER_INFO
    WHERE TO_CHAR(JOINED,'YYYY')='2021'
),
TOTAL_USER_CNT AS(
    SELECT COUNT(*) AS CNT FROM USER_2021
)
SELECT TO_CHAR(O.SALES_DATE, 'YYYY') AS YEAR,
    TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')) AS MONTH,
    COUNT(DISTINCT(O.USER_ID)) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT(O.USER_ID))/ T.CNT,1) AS PURCHASED_RATIO
FROM ONLINE_SALE O
    JOIN USER_2021 U ON O.USER_ID=U.USER_ID
    CROSS JOIN TOTAL_USER_CNT T
GROUP BY TO_CHAR(O.SALES_DATE, 'YYYY'), TO_CHAR(O.SALES_DATE, 'MM'), T.CNT
ORDER BY 1, 2;